In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 10)

print("Libraries loaded successfully.")

Libraries loaded successfully.

In [2]:
df = pd.read_csv("../data/raw/weather.csv")

print("Dataset Loaded Successfully!")
print(f"Rows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")

Dataset Loaded Successfully!
Rows: 151047
Columns: 41

In [3]:
df.head()

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,wind_mph,wind_kph,wind_degree,wind_direction,pressure_mb,pressure_in,precip_mm,precip_in,humidity,cloud,feels_like_celsius,feels_like_fahrenheit,visibility_km,visibility_miles,uv_index,gust_mph,gust_kph,air_quality_Carbon_Monoxide,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.52,69.18,Asia/Kabul,1715849100,2024-05-16 13:15,26.6,79.8,Partly Cloudy,8.3,13.3,338,NNW,1012.0,29.89,0.0,0.00,24,30,25.3,77.5,10.0,6.0,7.0,9.5,15.3,277.0,103.0,1.1,0.2,8.4,26.6,1,1,04:50 AM,06:50 PM,12:12 PM,01:11 AM,Waxing Gibbous,55
1,Albania,Tirana,41.33,19.82,Europe/Tirane,1715849100,2024-05-16 10:45,19.0,66.2,Partly cloudy,6.9,11.2,320,NW,1012.0,29.88,0.1,0.00,94,75,19.0,66.2,10.0,6.0,5.0,11.4,18.4,193.6,97.3,0.9,0.1,1.1,2.0,1,1,05:21 AM,07:54 PM,12:58 PM,02:14 AM,Waxing Gibbous,55
2,Algeria,Algiers,36.76,3.05,Africa/Algiers,1715849100,2024-05-16 09:45,23.0,73.4,Sunny,9.4,15.1,280,W,1011.0,29.85,0.0,0.00,29,0,24.6,76.4,10.0,6.0,5.0,13.9,22.3,540.7,12.2,65.1,13.4,10.4,18.4,1,1,05:40 AM,07:50 PM,01:15 PM,02:14 AM,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.50,1.52,Europe/Andorra,1715849100,2024-05-16 10:45,6.3,43.3,Light drizzle,7.4,11.9,215,SW,1007.0,29.75,0.3,0.01,61,100,3.8,38.9,2.0,1.0,2.0,8.5,13.7,170.2,64.4,1.6,0.2,0.7,0.9,1,1,06:31 AM,09:11 PM,02:12 PM,03:31 AM,Waxing Gibbous,55
4,Angola,Luanda,-8.84,13.23,Africa/Luanda,1715849100,2024-05-16 09:45,26.0,78.8,Partly cloudy,8.1,13.0,150,SSE,1011.0,29.85,0.0,0.00,89,50,28.7,83.6,10.0,6.0,8.0,12.5,20.2,2964.0,19.0,72.7,31.5,183.4,262.3,5,10,06:12 AM,05:55 PM,01:17 PM,12:38 AM,Waxing Gibbous,55

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 151047 entries, 0 to 151046
Data columns (total 41 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   country                       151047 non-null  str
 1   location_name                 151047 non-null  str
 2   latitude                      151047 non-null  float64
 3   longitude                     151047 non-null  float64
 4   timezone                      151047 non-null  str
 5   last_updated_epoch            151047 non-null  int64
 6   last_updated                  151047 non-null  str
 7   temperature_celsius           151047 non-null  float64
 8   temperature_fahrenheit        151047 non-null  float64
 9   condition_text                151047 non-null  str
 10  wind_mph                      151047 non-null  float64
 11  wind_kph                      151047 non-null  float64
 12  wind_degree                   151047 non-null  int64
 13  wind_direction                151047 non-null  str
 14  pressure_mb                   151047 non-null  float64
 15  pressure_in                   151047 non-null  float64
 16  precip_mm                     151047 non-null  float64
 17  precip_in                     151047 non-null  float64
 18  humidity                      151047 non-null  int64
 19  cloud                         151047 non-null  int64
 20  feels_like_celsius            151047 non-null  float64
 21  feels_like_fahrenheit         151047 non-null  float64
 22  visibility_km                 151047 non-null  float64
 23  visibility_miles              151047 non-null  float64
 24  uv_index                      151047 non-null  float64
 25  gust_mph                      151047 non-null  float64
 26  gust_kph                      151047 non-null  float64
 27  air_quality_Carbon_Monoxide   151047 non-null  float64
 28  air_quality_Ozone             151047 non-null  float64
 29  air_quality_Nitrogen_dioxide  151047 non-null  float64
 30  air_quality_Sulphur_dioxide   151047 non-null  float64
 31  air_quality_PM2.5             151047 non-null  float64
 32  air_quality_PM10              151047 non-null  float64
 33  air_quality_us-epa-index      151047 non-null  int64
 34  air_quality_gb-defra-index    151047 non-null  int64
 35  sunrise                       151047 non-null  str
 36  sunset                        151047 non-null  str
 37  moonrise                      151047 non-null  str
 38  moonset                       151047 non-null  str
 39  moon_phase                    151047 non-null  str
 40  moon_illumination             151047 non-null  int64
dtypes: float64(23), int64(7), str(11)
memory usage: 62.4 MB

In [5]:
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
country,151047,211,Bulgaria,1777,NaN,NaN,NaN,NaN,NaN,NaN,NaN
location_name,151047,268,Sanaa,778,NaN,NaN,NaN,NaN,NaN,NaN,NaN
latitude,151047.0,NaN,NaN,NaN,19.236939,24.401956,-41.3,4.0503,17.25,40.4,65.3
longitude,151047.0,NaN,NaN,NaN,21.893065,65.779522,-175.2,-6.8361,23.2361,49.8822,179.22
timezone,151047,201,Asia/Bangkok,2738,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
sunset,151047,564,06:28 PM,1413,NaN,NaN,NaN,NaN,NaN,NaN,NaN
moonrise,151047,1445,No moonrise,4838,NaN,NaN,NaN,NaN,NaN,NaN,NaN
moonset,151047,1445,No moonset,4749,NaN,NaN,NaN,NaN,NaN,NaN,NaN
moon_phase,151047,8,Waxing Gibbous,33350,NaN,NaN,NaN,NaN,NaN,NaN,NaN
moon_illumination,151047.0,NaN,NaN,NaN,50.235688,35.132799,0.0,15.0,51.0,85.0,100.0

In [6]:
missing = df.isnull().sum().sort_values(ascending=False)

missing[missing > 0]

Series([], dtype: int64)

In [7]:
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

In [8]:
for col in df.columns:
    print(col)

country
location_name
latitude
longitude
timezone
last_updated_epoch
last_updated
temperature_celsius
temperature_fahrenheit
condition_text
wind_mph
wind_kph
wind_degree
wind_direction
pressure_mb
pressure_in
precip_mm
precip_in
humidity
cloud
feels_like_celsius
feels_like_fahrenheit
visibility_km
visibility_miles
uv_index
gust_mph
gust_kph
air_quality_Carbon_Monoxide
air_quality_Ozone
air_quality_Nitrogen_dioxide
air_quality_Sulphur_dioxide
air_quality_PM2.5
air_quality_PM10
air_quality_us-epa-index
air_quality_gb-defra-index
sunrise
sunset
moonrise
moonset
moon_phase
moon_illumination

In [9]:
df["last_updated"] = pd.to_datetime(df["last_updated"])

df["year"] = df["last_updated"].dt.year
df["month"] = df["last_updated"].dt.month
df["day"] = df["last_updated"].dt.day
df["hour"] = df["last_updated"].dt.hour

df.head()

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,wind_mph,wind_kph,wind_degree,wind_direction,pressure_mb,pressure_in,precip_mm,precip_in,humidity,cloud,feels_like_celsius,feels_like_fahrenheit,visibility_km,visibility_miles,uv_index,gust_mph,gust_kph,air_quality_Carbon_Monoxide,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination,year,month,day,hour
0,Afghanistan,Kabul,34.52,69.18,Asia/Kabul,1715849100,2024-05-16 13:15:00,26.6,79.8,Partly Cloudy,8.3,13.3,338,NNW,1012.0,29.89,0.0,0.00,24,30,25.3,77.5,10.0,6.0,7.0,9.5,15.3,277.0,103.0,1.1,0.2,8.4,26.6,1,1,04:50 AM,06:50 PM,12:12 PM,01:11 AM,Waxing Gibbous,55,2024,5,16,13
1,Albania,Tirana,41.33,19.82,Europe/Tirane,1715849100,2024-05-16 10:45:00,19.0,66.2,Partly cloudy,6.9,11.2,320,NW,1012.0,29.88,0.1,0.00,94,75,19.0,66.2,10.0,6.0,5.0,11.4,18.4,193.6,97.3,0.9,0.1,1.1,2.0,1,1,05:21 AM,07:54 PM,12:58 PM,02:14 AM,Waxing Gibbous,55,2024,5,16,10
2,Algeria,Algiers,36.76,3.05,Africa/Algiers,1715849100,2024-05-16 09:45:00,23.0,73.4,Sunny,9.4,15.1,280,W,1011.0,29.85,0.0,0.00,29,0,24.6,76.4,10.0,6.0,5.0,13.9,22.3,540.7,12.2,65.1,13.4,10.4,18.4,1,1,05:40 AM,07:50 PM,01:15 PM,02:14 AM,Waxing Gibbous,55,2024,5,16,9
3,Andorra,Andorra La Vella,42.50,1.52,Europe/Andorra,1715849100,2024-05-16 10:45:00,6.3,43.3,Light drizzle,7.4,11.9,215,SW,1007.0,29.75,0.3,0.01,61,100,3.8,38.9,2.0,1.0,2.0,8.5,13.7,170.2,64.4,1.6,0.2,0.7,0.9,1,1,06:31 AM,09:11 PM,02:12 PM,03:31 AM,Waxing Gibbous,55,2024,5,16,10
4,Angola,Luanda,-8.84,13.23,Africa/Luanda,1715849100,2024-05-16 09:45:00,26.0,78.8,Partly cloudy,8.1,13.0,150,SSE,1011.0,29.85,0.0,0.00,89,50,28.7,83.6,10.0,6.0,8.0,12.5,20.2,2964.0,19.0,72.7,31.5,183.4,262.3,5,10,06:12 AM,05:55 PM,01:17 PM,12:38 AM,Waxing Gibbous,55,2024,5,16,9

In [10]:
df.dtypes

country                  str
location_name            str
latitude             float64
longitude            float64
timezone                 str
                      ...
moon_illumination      int64
year                   int32
month                  int32
day                    int32
hour                   int32
Length: 45, dtype: object

In [11]:
numeric_columns = df.select_dtypes(include=["int64", "float64"]).columns

print(f"Numeric Features: {len(numeric_columns)}")

numeric_columns

Numeric Features: 30

Index(['latitude', 'longitude', 'last_updated_epoch', 'temperature_celsius',
       'temperature_fahrenheit', 'wind_mph', 'wind_kph', 'wind_degree',
       'pressure_mb', 'pressure_in', 'precip_mm', 'precip_in', 'humidity',
       'cloud', 'feels_like_celsius', 'feels_like_fahrenheit', 'visibility_km',
       'visibility_miles', 'uv_index', 'gust_mph', 'gust_kph',
       'air_quality_Carbon_Monoxide', 'air_quality_Ozone',
       'air_quality_Nitrogen_dioxide', 'air_quality_Sulphur_dioxide',
       'air_quality_PM2.5', 'air_quality_PM10', 'air_quality_us-epa-index',
       'air_quality_gb-defra-index', 'moon_illumination'],
      dtype='str')

In [12]:
categorical_columns = df.select_dtypes(include=["object"]).columns

print(f"Categorical Features: {len(categorical_columns)}")

categorical_columns

Categorical Features: 10

/tmp/ipykernel_16459/4017547308.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(include=["object"]).columns

Index(['country', 'location_name', 'timezone', 'condition_text',
       'wind_direction', 'sunrise', 'sunset', 'moonrise', 'moonset',
       'moon_phase'],
      dtype='str')

In [13]:
Q1 = df["temperature_celsius"].quantile(0.25)
Q3 = df["temperature_celsius"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[
    (df["temperature_celsius"] < lower) |
    (df["temperature_celsius"] > upper)
]

print("Temperature Outliers:", len(outliers))

Temperature Outliers: 2647

In [14]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaled = scaler.fit_transform(
    df[[
        "temperature_celsius",
        "humidity",
        "wind_kph",
        "pressure_mb"
    ]]
)

scaled.shape

(151047, 4)